#!/bin/env python

# this is a development placeholder, use entrypoints!

import sys
import multiprocessing

if __name__ == '__main__':
    multiprocessing.freeze_support()

    import hexedd
    print hexedd.__version__

    sys.exit(main())
